<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $type
 * @property string $title
 * @property string $image
 * @property string $body
 * @property string $location
 * @property boolean $is_featured
 * @property integer $sort_order
 * @property boolean $is_active
 * 
 * @method integer getType()        Returns the current record's "type" value
 * @method string  getTitle()       Returns the current record's "title" value
 * @method string  getImage()       Returns the current record's "image" value
 * @method string  getBody()        Returns the current record's "body" value
 * @method string  getLocation()    Returns the current record's "location" value
 * @method boolean getIsFeatured()  Returns the current record's "is_featured" value
 * @method integer getSortOrder()   Returns the current record's "sort_order" value
 * @method boolean getIsActive()    Returns the current record's "is_active" value
 * @method News    setType()        Sets the current record's "type" value
 * @method News    setTitle()       Sets the current record's "title" value
 * @method News    setImage()       Sets the current record's "image" value
 * @method News    setBody()        Sets the current record's "body" value
 * @method News    setLocation()    Sets the current record's "location" value
 * @method News    setIsFeatured()  Sets the current record's "is_featured" value
 * @method News    setSortOrder()   Sets the current record's "sort_order" value
 * @method News    setIsActive()    Sets the current record's "is_active" value
 * 
 * @package    easy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 1,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('location', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('is_featured', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('sort_order', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}