<?php

/**
 * BaseJobCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Jobs
 * 
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getJobs() Returns the current record's "Jobs" collection
 * @method JobCategory         setName() Sets the current record's "name" value
 * @method JobCategory         setJobs() Sets the current record's "Jobs" collection
 * 
 * @package    easy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Job as Jobs', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}