<?php

/**
 * JobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobTable extends Doctrine_Table
{

    static public $types = array(
        'freelancer' => 'Freelance',
        'full-time'  => 'Full-Time',
        'internship' => 'Internship',
        'part-time'  => 'Part-Time',
        'temporary'  => 'Temporary',
  );

  static public $i18nTypes = array(
        'freelancer'=> 'Хувиараа',
        'full-time' => 'Бүтэн цагийн',
        'internship'=> 'Дадлагын',
        'part-time' => 'Цагийн',
        'temporary' => 'Түр зуурын',
  );

  public function getTypes()
  {
    return self::$types;
  }

  public function getI18nTypes()
  {
    return self::$i18nTypes;
  }

  public function getI18nType($key)
  {
    return isset(self::$i18nTypes[$key]) ? self::$i18nTypes[$key]: '';
  }

    /**
     * Returns an instance of this class.
     *
     * @return object JobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Job');
    }


}