<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }

    public function getUserByNamePassword($username, $password)
    {
        $q = Doctrine_Query::create()
                ->select('u.*')
                ->from('User u')
                ->where('u.username = ?', $username)
                ->andWhere('u.password = ?', sha1($password));

        return $q->fetchOne();

    }
}